### ISSUE TITLE
How can I tweak the model?

### ISSUE THREAD

**Issue by kehphin** [bureaucratic-labs/revizor#2]
Hi dveselov,

Great library! I'm looking to tweak the model with a dataset of my own (~100k product titles and metadata). How can I do so? I see your `.pt` model file but can't find the code you used to generate it. 

Thanks 😄

**Comment by dveselov** [comment]
Hi, additional training / finetuning isn't available for this library.  
But, you can follow [training tutorials for flair library](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md), which is used in this package.
